name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: build the OSM proejct
        run: ls && cd Applytics_SDK && npm install && npm run build
      - name: executing remote git pull and restart pm2
        uses: appleboy/ssh-action@master
        with:
          host: test.applytics.in
          username: albin_git
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: ls && ls -alt
